package org.nalby.yobatis.mybatis;

import java.io.IOException;
import java.io.InputStream;
import java.util.LinkedList;
import java.util.List;

import org.mybatis.generator.api.GeneratedJavaFile;
import org.mybatis.generator.api.GeneratedXmlFile;
import org.mybatis.generator.api.LibraryRunner;
import org.mybatis.generator.exception.InvalidConfigurationException;
import org.nalby.yobatis.exception.InvalidMybatisGeneratorConfigException;
import org.nalby.yobatis.exception.ProjectException;
import org.nalby.yobatis.log.LogFactory;
import org.nalby.yobatis.log.Logger;
import org.nalby.yobatis.structure.File;
import org.nalby.yobatis.structure.Project;
import org.nalby.yobatis.util.Expect;
import org.nalby.yobatis.xml.SqlMapperParser;

/**
 * Write files generated by MyBatis Generator to corresponding directories.
 * @author Kyle Lin
 */
public class MybatisFilesWriter {

	private LibraryRunner runner;

	private MybatisConfigReader reader;

	private Project project;
	
	private Logger logger = LogFactory.getLogger(MybatisFilesWriter.class);

	public MybatisFilesWriter(Project project, MybatisConfigReader configReader) {
		Expect.notNull(project, "project must not be null.");
		Expect.notNull(configReader, "configReader must not be null.");
		this.project = project;
		this.runner = new LibraryRunner();
		try {
			File file = project.findFile(MybatisConfigReader.CONFIG_FILENAME);
			try (InputStream inputStream = file.open()) {
				this.runner.parse(inputStream);
			}
		} catch (InvalidConfigurationException e) {
			throw new InvalidMybatisGeneratorConfigException(e);
		} catch (IOException e) {
			throw new InvalidMybatisGeneratorConfigException(e);
		}
		if (runner.getGeneratedJavaFiles() == null) {
			throw new ProjectException("No java files generated.");
		}
		if (runner.getGeneratedXmlFiles() == null) {
			throw new ProjectException("No xml files generated.");
		}
		this.reader = configReader;
	}

	private List<GeneratedJavaFile> listFile(String suffix) {
		List<GeneratedJavaFile> result = new LinkedList<GeneratedJavaFile>();
		List<GeneratedJavaFile> javaFiles = runner.getGeneratedJavaFiles();
		for (GeneratedJavaFile file : javaFiles) {
			if (file.getFileName() != null
					&& file.getFileName().endsWith(suffix)) {
				result.add(file);
			}
		}
		return result;
	}

	private List<GeneratedJavaFile> getMapperFiles() {
		return listFile("Mapper.java");
	}
	
	private List<GeneratedJavaFile> getCriteriaFiles() {
		return listFile("Criteria.java");
	}

	public List<GeneratedJavaFile> getDomainFiles() {
		List<GeneratedJavaFile> javaFiles = runner.getGeneratedJavaFiles();
		List<GeneratedJavaFile> result = new LinkedList<GeneratedJavaFile>();
		for (GeneratedJavaFile file : javaFiles) {
			if (file.getFileName() != null &&
				(!file.getFileName().endsWith("Mapper.java") &&
				 !file.getFileName().endsWith("Criteria.java"))) {
				result.add(file);
			}
		}
		return result;
	}
	
	private List<GeneratedXmlFile> getXmlFiles() {
		return runner.getGeneratedXmlFiles();
	}
	
	private void writeJavaMappers() {
		List<GeneratedJavaFile> files = getMapperFiles();
		for (GeneratedJavaFile javafile : files) {
			String path = reader.getDaoDirPath() + "/" + javafile.getFileName();
			if (project.findFile(path) != null) {
				continue;
			}
			File tmp = project.createFile(path);
			tmp.write(javafile.getFormattedContent());
		}
		logger.info("Worte java mapper files to :{}.", reader.getDaoDirPath());
	}
	
	private void writeJavaDomains() {
		List<GeneratedJavaFile> files = getDomainFiles();
		for (GeneratedJavaFile javafile : files) {
			String path = reader.getDomainDirPath() + "/" + javafile.getFileName();
			File tmp = project.createFile(path);
			tmp.write(javafile.getFormattedContent());
		}
		logger.info("Worte model files to :{}.", reader.getDomainDirPath());
	}
	
	private void writeCriteriaFiles() {
		List<GeneratedJavaFile> files = getCriteriaFiles();
		for (GeneratedJavaFile javafile : files) {
			String path = reader.getCriteriaDirPath() + "/" + javafile.getFileName();
			File tmp = project.createFile(path);
			tmp.write(javafile.getFormattedContent());
		}
		logger.info("Worte criteria files to :{}.", reader.getCriteriaDirPath());
	}
	
	private String mergeManualSqlXml(String path, String content) {
		try {
			File file = project.findFile(path);
			try (InputStream inputStream = file.open()) {
				SqlMapperParser oldXml = new SqlMapperParser(inputStream);
				SqlMapperParser newXml = SqlMapperParser.fromString(content);
				newXml.merge(oldXml);
				return newXml.toXmlString();
			}
		} catch (Exception e) {
			return content;
		}
	}
	
	private void writeXmlFiles() {
		List<GeneratedXmlFile> xmlFiles = getXmlFiles();
		for (GeneratedXmlFile xmlfile : xmlFiles) {
			String path = reader.getXmlMapperDirPath() + "/" + xmlfile.getFileName();
			File tmp = project.createFile(path);
			tmp.write(mergeManualSqlXml(path, xmlfile.getFormattedContent()));
		}
		logger.info("Worte xml mapper files to :{}.", reader.getXmlMapperDirPath());
	}

	public void writeAll() {
		writeCriteriaFiles();
		writeJavaDomains();
		writeJavaMappers();
		writeXmlFiles();
	}

}
